### ISSUE TITLE
I just wonder abt the hardware and software serial port

### ISSUE THREAD

**Issue by consolacion** [volca/cactus_micro_trial#1]
I was just wondering whether you use the hardware or the software serial port to connect to your ESP. Searching for the ">" in de SoftSerial stream suggests that that is where you connect your ESP8266, but other parts  suggest it  is the hardware serial port where you connect your ESP

**Comment by volca** [comment]
Hi,

It's an example for cactus micro rev1. The rev1 use softSerial to communicate with ESP. If you asked for cactus micro rev2, the sketch can't work directly.

**Comment by consolacion** [comment]
ok tnx. good to know
